# 참조 - https://heehee-myblog.tistory.com/3

name: Metrics
on:
  # schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-left.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: >- 
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          token: ${{ secrets.METRIC }}
